# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-21 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_image', models.ImageField(upload_to=b'photos/')),
                ('post_caption', models.CharField(max_length=300)),
                ('upload_by', models.CharField(max_length=30)),
            ],
        ),
    ]
