# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-22 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gram', '0002_comment_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default=b'default.jpg', upload_to=b'profiles/'),
        ),
    ]
