# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-22 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gram', '0004_auto_20191022_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='upload_by',
            field=models.CharField(max_length=30),
        ),
    ]
