# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-24 18:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gram', '0007_auto_20191024_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='unlikes',
            field=models.ManyToManyField(blank=True, related_name='unlikes', to=settings.AUTH_USER_MODEL),
        ),
    ]
